### PR TITLE
docs: add demo to readme

### PR DESCRIPTION
**Pull request by joshka**
Uses https://github.com/charmbracelet/vhs to run the example

Demo

P.S. this widget looks awesome!

### CODE REVIEW

**Review by leejseo — APPROVED** [review]
LGTM

**Comment by codingskynet** [comment]
@joshka Thanks you for adding beautiful demo gif!

**Comment by joshka** [comment]
No problem. Let me know when you make a release and I'll add it to the widget showcase on https://ratatui.rs (my local PR is awaiting a crate link ;))

If the ship hasn't already sailed, a lot of libs still tend to use the shorter tui- prefix for their name. I have a few myself: tui-bigtext, tui-prompts, and tui-popup (released just the other day). Your call, but I prefer the shorten name for widget crates.

Come drop a link in the made with ratatui channel on the discord whichever when you do release.

Feel free to steal the release automation from my repos - it's an easy way to fall into a pot of release success for a small library.

**Comment by codingskynet** [comment]
@joshka Ok, I will change to shorter name, and will notify when it is released. Thanks for a lot of attention!

**Comment by joshka** [comment]
Not a problem - good luck :)

**Pull request merged**
